Repository UBC-MDS/DSCI-532_2025_11_world_happiness, pull requests merged in 2025-03, with the labels that each got.

#58 Update m2-reflection.md
  reports/m2-reflection.md
Labels: documentation, enhancement

#90 Replace year dropdown with slidebar
  src/components/callbacks.py
  src/components/dropdowns.py
  src/components/layout.py
  src/components/sliders.py
Labels: enhancement

#92 Map_fix to develop
  src/app.py
  src/components/charts.py
Labels: enhancement

#89 Fix dataset issues
  data/processed/World_Happiness_processed_data.csv
  data/processed/reporting_happiness_dataset.csv
  notebooks/Happiness_data_ETL_pipeline.ipynb
  src/components/data.py
Labels: bug, enhancement

#122 Update dataset and add parquet files
  data/processed/World_Happiness_processed_data.csv
  data/processed/World_Happiness_processed_data.parquet
  data/processed/world_countries.csv
  data/processed/world_countries.parquet
  notebooks/Happiness_data_ETL_pipeline.ipynb
Labels: bug, enhancement

#124 replace download and read from url directly to read only the necessar…
  src/assets/scroll.js
  src/assets/styles.css
  src/components/callbacks.py
  src/components/data.py
  src/components/layout.py
  src/components/sliders.py
Labels: enhancement
